version: '3.9'

services:
  node:
    build: .
    container_name: project_node
    ports:
      - "5000:5000"
  pgdb:
    container_name: pg_database
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=password

